# Generated by Django 4.1.4 on 2023-02-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('blockname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor', to='infrastructure.block')),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('Condition', models.CharField(choices=[('Working', 'Working'), ('Repair', 'Repair'), ('Fixed', 'Fixed')], default='Working', max_length=100, null=True)),
                ('installed_date', models.DateField(auto_now=True)),
                ('Floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.floors')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed', to='infrastructure.floors')),
                ('reserved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientbed', to='patients.patients')),
            ],
        ),
    ]
