# Generated by Django 4.1.4 on 2023-01-16 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_medicalconditions_detail'),
        ('infrastructure', '0002_machines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='reserved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientbed', to='patients.patients'),
        ),
    ]
