# Generated by Django 4.1.4 on 2023-01-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_alter_bed_reserved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed', to='infrastructure.floors'),
        ),
        migrations.AlterField(
            model_name='floors',
            name='blockname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor', to='infrastructure.block'),
        ),
    ]
