# Generated by Django 4.1.4 on 2023-02-05 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_of_join', models.DateField()),
                ('phonenumber', models.IntegerField(null=True)),
                ('bloodGroup', models.CharField(max_length=5, null=True)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/staffs')),
                ('status', models.CharField(choices=[('Security', 'Security'), ('Attender', 'Attender'), ('Receptionist', 'Receptionist'), ('Manager', 'Manager'), ('Labassistant', 'Labassistant'), ('Helper', 'Helper')], max_length=120, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_of_join', models.DateField()),
                ('phonenumber', models.IntegerField(null=True)),
                ('bloodGroup', models.CharField(max_length=5, null=True)),
                ('age', models.IntegerField()),
                ('status', models.CharField(choices=[('new', 'new'), ('Senior', 'Senior'), ('HeadNurse', 'HeadNurse')], default='new', max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/Nurse')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_of_join', models.DateField()),
                ('specialized_in', models.CharField(max_length=150, null=True)),
                ('phonenumber', models.CharField(max_length=15, null=True)),
                ('bloodGroup', models.CharField(max_length=5, null=True)),
                ('age', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('new', 'new'), ('Senior', 'Senior'), ('Experienced', 'Experienced')], default='new', max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/Doctors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
