# Generated by Django 4.1.4 on 2022-12-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_of_join', models.DateField()),
                ('phonenumber', models.IntegerField(null=True)),
                ('bloodGroup', models.CharField(max_length=5, null=True)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/Security')),
                ('status', models.CharField(choices=[('Security', 'Security'), ('Attender', 'Attender'), ('Receptionist', 'Receptionist'), ('Manager', 'Manager'), ('Labassistant', 'Labassistant'), ('Helper', 'Helper')], max_length=120, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='attenders',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='helpers',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='labassistant',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='others',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='receptionist',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='security',
        ),
        migrations.DeleteModel(
            name='Attenders',
        ),
        migrations.DeleteModel(
            name='Helpers',
        ),
        migrations.DeleteModel(
            name='Labassistant',
        ),
        migrations.DeleteModel(
            name='Managers',
        ),
        migrations.DeleteModel(
            name='Others',
        ),
        migrations.DeleteModel(
            name='Receptionist',
        ),
        migrations.DeleteModel(
            name='Security',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
