# Generated by Django 4.1.4 on 2022-12-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_doctor_created_by_alter_doctor_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.CharField(max_length=6),
        ),
    ]
