# Generated by Django 4.1.4 on 2022-12-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_doctor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(null=True, upload_to='images/Doctors'),
        ),
    ]
