# Generated by Django 5.2 on 2025-04-18 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(blank=True, choices=[('Diagnosis', 'Diagnosis'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Diagnosis', max_length=100)),
                ('admitted', models.BooleanField(default=False)),
                ('time', models.DateField(auto_now_add=True)),
                ('is_alloted', models.BooleanField(default=False)),
                ('doctors', models.ManyToManyField(default='OP', related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_medicine', models.TextField(blank=True, null=True)),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='patients.patients')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=1000)),
                ('detail', models.CharField(blank=True, max_length=2000, null=True)),
                ('testreports', models.CharField(blank=True, max_length=150)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_conditions', to='patients.patients')),
            ],
        ),
    ]
