# Generated by Django 4.1.4 on 2022-12-22 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Diagnosis', 'Diagnosis'), ('Admitted', 'Admitted'), ('Discharge', 'Discharge')], default='Diagnosis', max_length=100, null=True)),
                ('admitted', models.BooleanField(default=False)),
                ('medical_condition', models.CharField(max_length=1000)),
                ('time', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(default='OP', null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=1000)),
                ('testreports', models.CharField(max_length=150)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
            ],
        ),
    ]
