# Generated by Django 4.1.4 on 2023-02-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Diagnosis', 'Diagnosis'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Diagnosis', max_length=100, null=True)),
                ('admitted', models.BooleanField(default=False)),
                ('time', models.DateField(auto_now_add=True)),
                ('alloted', models.BooleanField(default=False)),
                ('doctors', models.ManyToManyField(default='OP', null=True, to='staff.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=1000)),
                ('detail', models.CharField(max_length=2000, null=True)),
                ('testreports', models.CharField(max_length=150)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ManyToManyField(null=True, related_name='patient', to='patients.patients')),
            ],
        ),
    ]
