# Generated by Django 4.1.4 on 2023-01-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='alloted',
            field=models.BooleanField(default=False),
        ),
    ]
