# Generated by Django 4.1.4 on 2023-01-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_doctor_image'),
        ('patients', '0002_patients_alloted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patients',
            name='doctors',
            field=models.ManyToManyField(default='OP', null=True, to='staff.doctor'),
        ),
        migrations.RemoveField(
            model_name='medicalconditions',
            name='patient',
        ),
        migrations.AddField(
            model_name='medicalconditions',
            name='patient',
            field=models.ManyToManyField(to='patients.patients'),
        ),
    ]
