# Generated by Django 4.1.4 on 2023-01-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_medicalconditions_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalconditions',
            name='detail',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
