# Generated by Django 4.1.4 on 2023-01-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_medicalconditions_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalconditions',
            name='patient',
            field=models.ManyToManyField(null=True, related_name='patient', to='patients.patients'),
        ),
        migrations.RemoveField(
            model_name='patients',
            name='medical_condition',
        ),
        migrations.AddField(
            model_name='patients',
            name='medical_condition',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
