# Generated by Django 4.1.4 on 2023-01-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_patients_medical_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='status',
            field=models.CharField(choices=[('Diagnosis', 'Diagnosis'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Diagnosis', max_length=100, null=True),
        ),
    ]
